#!/bin/bash
# Author: Simple Finance <ops@simple.com>
# License: Apache License, Version 2.0
#
# Copyright 2013 Simple Finance Technology Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -- $(wal-e backup-list LATEST | tail -1)
name=$1
last_modified=$2

if [ -z "$last_modified" ]; then
   echo "CRITICAL - `wal-e backup-list` returned no backups"
   exit 2
fi

now=$(date +%s)
last_modified_epoch=$(date --date="$last_modified" +%s)
diff=$(($now - $last_modified_epoch))
tolerance=$((60 * 60 * 24 * 7 + (2 * 60 * 60)))

if [ "$diff" -gt "$tolerance" ]; then
   echo "CRITICAL - wal-e last full backup exceeds tolerance: $last_modified"
   exit 2
fi

echo "wal-e last full backup ok: $last_modified"
exit 0
